

views:
  - name: ai360CDPView
    description: "AI360 CDP"
    ####join cubes
    cubes:
      - join_path: AI360CDP
        includes:
          - "*"
      - join_path: demo_gold_dimensions.dim_communications
        includes:
          - "*"
    includes:
      - AI360CDP.count_customers
    dimensions:
      - name: cif_id
        sql: "{AI360CDP.cif_id}"
        type: string
      - name: first_name
        sql: "{AI360CDP.cust_first_name}"
        type: string

      - name: last_name
        sql: "{AI360CDP.cust_last_name}"
        type: string
      - name: full_name
        sql: "{AI360CDP.full_name}"
        type: string
      - name: address_line
        sql: "{AI360CDP.address_line}"
        type: string
      - name: cust_type
        sql: "{AI360CDP.cust_type}"
        type: string
      - name: dob
        sql: "{AI360CDP.cust_dob}"
        type: time
      - name: gender
        sql: "{AI360CDP.gender}"
        type: string
      - name: employment_status
        sql: "{AI360CDP.employment_status}"
        type: string
      - name: age
        sql: "{AI360CDP.age}"
        type: number
      - name: occupation
        sql: "{AI360CDP.occupation}"
        type: string
      - name: email
        sql: "{demo_gold_dimensions.dim_communications.dim_communications.email}"
        type: string

      