cubes:
  - name: dim_mob_application_user
    sql_table: gold_dimensions.dim_mob_application_user
    data_source: default

    joins: []

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

      - name: application_user_sk
        sql: application_user_sk
        type: string
      - name: mobile_number
        sql: mobile_number
        type: string
      
      - name: account_number
        sql: account_number
        type: string

      - name: foracid_sk
        sql: foracid_sk
        type: string
      - name: customer_id_sk
        sql: customer_id_sk
        type: string

      - name: branch_sol_sk
        sql: branch_sol_sk
        type: string

      - name: created_date
        sql: created_date
        type: string

      - name: last_modified_date
        sql: last_modified_date
        type: string

      - name: last_login_time
        sql: last_login_time
        type: string

      - name: login_block_date
        sql: login_block_date
        type: string

      - name: login_block_remarks
        sql: login_block_remarks
        type: string

      - name: dbt_scd_id
        sql: dbt_scd_id
        type: string

      - name: dbt_updated_at
        sql: dbt_updated_at
        type: string

      - name: dbt_valid_from
        sql: dbt_valid_from
        type: string

      - name: dbt_valid_to
        sql: dbt_valid_to
        type: string

      - name: created_date_date_part
        sql: created_date_date_part
        type: time

      - name: last_modified_date_date_part
        sql: last_modified_date_date_part
        type: time

      - name: last_login_time
        sql: last_login_time
        type: time

      - name: login_block_date
        sql: login_block_date
        type: time

    measures:
      - name: count
        type: count

      - name: request_attempt_count
        sql: request_attempt_count
        type: sum

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

